### ISSUE TITLE
Find a way to check if the port is open prior to activating TABSIE

### ISSUE THREAD

**Issue by bokov** [UTHSCSA-CIRD/GPC-Weight-Health-Survey#26]
Just got a report of an error where the relevant output was:

```
C:\1staging\GPCHWdataset>R-Portable\App\R-Portable\bin\Rscript.exe %ROPTS% runShinyApp.R
Loading required package: shiny
Loading required package: methods

Listening on http://127.0.0.1:8888
Error in startServer(host, port, handlerManager$createHttpuvApp()) :
Failed to create server
Calls: <Anonymous> -> startApp -> startServer
Execution halted

C:\1staging\GPCHWdataset>
```

According to [stackoverflow](http://stackoverflow.com/a/19639607/945039) this can be fixed with 
`devtools::install_github(c("shiny", "httpuv"), "rstudio")` 
However, just checked and the `devtools` library is not part of our R-Portable. I have a workaround for him by invoking...
`R -e "install.packages('devtools',repo='https://cran.rstudio.com/');devtools::install_github(c('shiny', 'httpuv'), 'rstudio')"`
...at the comand-line. Still, `devtools` has useful stuff for portable app wrangling.

**Comment by Milanara** [comment]
The following error is caused by another process already listening on the port. This could be caused by 2 instances of TABSIE trying to run at the same time (one is open and they double click the .bat file again) OR by another app using the same port. There is a command where shiny chooses a random unused port, but this didn't work when I tested it. Possibly because our IS department closes some ports.

Listening on http://127.0.0.1:8888
Error in startServer(host, port, handlerManager$createHttpuvApp()) : 
  Failed to create server
Calls: <Anonymous> -> startApp -> startServer
Execution halted

**Comment by Milanara** [comment]
Found out how to warn if another TABSIE is currently running. 

```
netstat -o -n -a | findstr :8888
if ERRORLEVEL 1 (
echo Initializing...
SET ROPTS=--no-save --no-environ --no-init-file --no-restore --no-Rconsole
R-Portable\App\R-Portable\bin\Rscript.exe %ROPTS% runShinyApp.R 1> NUL 2>&1
) ELSE (
echo ERROR! Another application is currently using port 8888
pause)
```
