### ISSUE TITLE
The "Only Survey 2 Respondents?" checkbox is also relevant to the graphs tab and should be visible there

### ISSUE THREAD

**Issue by bokov** [UTHSCSA-CIRD/GPC-Weight-Health-Survey#9]
The "Only Survey 2 Respondents?" is not redundant removing the empty X and/or Y values, and is the real contributor to oversized "missing" bars that drown out the other results.

We might want to see the missing responses but only among the people who otherwise did answer some of survey2.

**Comment by Milanara** [comment]
Alright, this was a fun fix. Because some of the graphing options will automatically omit null/na values and our current filter omits pretty much the same null values I added a generic "enable/disable" option for the filter check box. NOTE: this makes a few assumptions about later programming decisions:
1- There will only be one active filter at a time. 
2- There exists a dataset "filtered" which is cached to minimize the work of filtering repeatedly (as would happen a lot with shiny). (This should be easy enough to circumvent, but circumventing it is not advisable for large data sets where filtering repeatedly may take on the magnitude of seconds.)
